---
- name: "update local apt repo."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "remove stale dependencies1"
  become: true
  apt:
    autoremove: yes
    


#- name: "copy files from CircleCI to server"
 # copy:
#    src: /root/project/backend
#    dest: /home/ubuntu

- name: extract artifact
  become: true
  unarchive:
    src: /root/project/backend/artifact.tar.gz
    dest: /home/ubuntu
    
- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 
    npm run build

- name: "Start app"
  become: true
  shell: |
    cd /home/ubuntu
    pm2 stop all
    pm2 start npm -- run "start:dev"

  environment:
  #Environement Variables and Values
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    ENVIRONMENT: PRODUCTION
